#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch="^(feature\/[a-zA-Z0-9._-]+|hotfix\/[a-zA-Z0-9._-]+|master|develop|DEVELOPMENT)+$"
message="The branch name is incorrect. Branch name should be of the format feature/ or release/ or hotfix/ . Please rename your branch."

if ! echo "$branch" | grep -Eq "$valid_branch"; then
  echo "$message"
  exit 1
fi

# Ensure the path to husky.sh is correct
. "$(dirname "$0")/../.husky/_/husky.sh"

yarn lint-staged

exit 0
